administracionScazac/urls.py
from django.conf.urls import include, url
from django.views.generic import TemplateView
from account.decorators import login_required
from administracionScazac.views import MonitoringMapAdminView, MonitoringStationViewAdd, MonitoringStationViewModify, MonitoringDataViewAdd, MonitoringDataViewDelete

app_name = 'administracion'

urlpatterns = [
    url(r"^adminmapa$",login_required(MonitoringMapAdminView.as_view()), name="mapa"),
    url(r"^adminstationadd$",login_required(MonitoringStationViewAdd.as_view()), name="stationAdd"),
    url(r"^adminstationmodify$",login_required(MonitoringStationViewModify.as_view()), name="stationModify"),
    url(r"^admindata$",login_required(MonitoringDataViewAdd.as_view()), name="dataAdd"),
    url(r"^admindatadelete$",login_required(MonitoringDataViewDelete.as_view()), name="dataDelete"),
]

investigacion/urls.py
from django.conf.urls import include, url
from django.views.generic import TemplateView
from investigacion.views import Principal, GraphsRecordView, NormativityView
from account.decorators import login_required
from . import views

app_name = 'investigacion'

urlpatterns = [
    url(r"^$",login_required(Principal.as_view()), name="principal"),
    url(r"^historial$",login_required(GraphsRecordView.as_view()), name="historial"),
    url(r"^normatividad$",login_required(NormativityView.as_view()), name="normatividad"), # Added 20171001 Url to requirment F2-5
]

scazac/urls.py
# Report of Modifications
# Modification 20170723: Givesd the root URL to the calidadAire app to handle.
# 20170924: URL from requirment F3 handle by investigacion
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.views.generic import TemplateView
from django.contrib import admin
import calidadAire.views
admin.site.site_header = r'SCAZAC|Administracion a bajo nivel'

urlpatterns = [
    url(r"^$", calidadAire.views.index, name='home'),#              
    url(r"^", include("calidadAire.urls")),                # 
    url(r"^lowleveladmin/", include(admin.site.urls)),     # Modified 20171016: The admin used by default on django will be LowLevel ence the url
    url(r"^usuario/", include("account.urls")),
    url(r"^admin/", include("administracionScazac.urls")),
    url(r"^investigacion/", include("investigacion.urls")), # Added 20170924
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

scazac/templates/_account_bar.html
{% load i18n %}
{% load account_tags %}
<!-- Modified 20170910: Hardcoded the color of all the text to white -->
<!-- Modified 20171001: Link to requirment F2-6 changed and F2-5 added. -->
<!-- Modified 20171016: Added Admin section (Requirment F3) -->
<!-- Modified 20171025: Hardcoded the las F3 requirment in order to use the lowlevel admin site to no replicate the function in another view -->
<ul class="nav navbar-nav pull-right"> <!--nav navbar-nav pull-right   -->
  {% if request.user.is_authenticated %}
  <p style="color: white;" class="navbar-text">
    <i style="color: white;" class="fa fa-user"></i> {% user_display request.user %}
  </p>
  <li>
    <a style="color: white;" href="{% url 'investigacion:principal' %}"><i class="fa fa-bar-chart-o"></i>Graficas</a>
  </li>
  <li>
    <a style="color: white;" href="{% url 'investigacion:historial' %}"><i class="fa fa-archive"></i>Historial de Graficas y Reportes</a> <!-- Added 20171001 User page to review saved graphs:Changed 20171001 Added the requirment F2-6 -->
  </li>
  <li>
    <a style="color: white;" href="{% url 'investigacion:normatividad' %}"><i class="fa fa-file-text"></i>Cumplimiento de Normatividad</a> <!-- Changed 20171001 Removed link to requirment F2-6 to requirment F2-5 -->
  </li>
    {% if request.user.is_superuser %} <!-- Modified 20171016: Added admin section (Check for admin authenticitie) -->
  <li>
    <a style="color: white;" href="{% url 'administracion:mapa' %}"><i class="fa fa-map-marker"></i>Admin: Mapa Principal</a>
  </li>
  <li>
    <a style="color: white;" href="{% url 'administracion:stationAdd' %}"><i class="fa fa-map-marker"></i>Admin: Estaciones de Monitoreo (Agregar)</a>
  </li>
  <li>
    <a style="color: white;" href="{% url 'administracion:stationModify' %}"><i class="fa fa-map-marker"></i>Admin: Estaciones de Monitoreo (Modificar/Borrar)</a>
  </li>
  <li>
    <a style="color: white;" href="{% url 'administracion:dataAdd' %}"><i class="fa fa-floppy-o"></i>Admin: Datos de monitoreo(Añadir)</a>
  </li>
    <li>
    <a style="color: white;" href="{% url 'administracion:dataDelete' %}"><i class="fa fa-floppy-o"></i>Admin: Datos de monitoreo(Borrar)</a>
  </li>
  <li>
    <a style="color: white;" href="/lowleveladmin/calidadAire/monitoringreports/"><i class="fa fa-tablet"></i>Admin: Reportes de la Calidad del Aire</a>
  </li>
  {% endif %}
  <li>
    <a style="color: white;" href="{% url 'account_settings' %}"><i class="fa fa-cog"></i> {% trans "Settings" %}</a>
  </li>
  <li>
    <a style="color: white;" id="account_logout" href="{% url 'account_logout' %}"><i class="fa fa-power-off"></i> {% trans "Log out" %}</a>
  </li>
  {% else %}
  <li class="scazacBar"><a style="color: white;" href="{% url 'account_login' %}">{% trans "Log in" %}</a></li>
  {% if ACCOUNT_OPEN_SIGNUP %}
  <li><a href="{% url 'account_signup' %}">{% trans "Sign up" %}</a></li>
  {% endif %}
  {% endif %}
</ul>

<form id="accountLogOutForm" style="display: none;" action="{% url 'account_logout' %}" method="POST">
  {% csrf_token %}
</form>

scazac/templates/_footer.html
{% load i18n %}
<!-- Modificado 20170910 -->
{% trans "&copy; 2017 &lt;Universidad Autonoma de Zacatecas&gt;" %}

scazac/templates/_scripts.html
<script src='/site_media/static/js/site-5e73bbeeb0.js'></script>

scazac/templates/_styles.html
<link href='/site_media/static/css/site-e7b87bbea0.css' rel='stylesheet' />
<style>/* Added 20170910: Change the color of the bar */
  .scazacBar{
  background-color: #00b0eb;
  color: #FFFFFF;
  }
  
</style>
{% if request.user.is_superuser %} <!-- Modified 20171016: Added padding to the  body to make room to the admin menu options-->
<!-- Modified 20171025: Added 50px more to the view becausse the bar greow a litte more since the lasst time -->
<style>
  body {
    padding-top: 250px;
  }
  @media (max-width: 768px) {
  body {
      padding-top: 60px;
    }
  }
</style>
{% endif %}

scazac/templates/homepage.html
{% extends "site_base.html" %}

{% load i18n %}

{% block head_title %}pinax-project-account{% endblock %}

{% block body_class %}home{% endblock %}

{% block body_base %}
    <section class="jumbotron">
        <div class="container">
            {% include "_messages.html" %}
            <h1>{% blocktrans %}Welcome to<br>pinax-project-account{% endblocktrans %}</h1>
            <p>
                {% blocktrans %}
                In addition to what is provided by the "zero" project, this project
                provides thorough integration with django-user-accounts, adding
                comprehensive account management functionality. It is a foundation
                suitable for most sites that have user accounts.
                {% endblocktrans %}
            </p>
            {% if not user.is_authenticated %}
            {% url "account_login" as login_url %}
            {% url "account_signup" as signup_url %}
            <p>{% blocktrans %}You can <a href="{{ login_url }}" class="btn btn-default">Log In</a> or <a href="{{ signup_url }}" class="btn btn-primary">Sign Up</a> to try out the site.{% endblocktrans %}</p>
            {% endif %}
        </div>
    </section>
    <section>
        <div class="container">
            <h2 class="text-center">{% blocktrans %}What is Pinax?{% endblocktrans %}</h2>
            <p class="lead">
                {% blocktrans %}
                <b>Pinax</b> is an open-source platform based on Django and
                intended to provide a starting point for websites. It takes
                care of the things that many sites have in common, so you can
                focus on what makes your site different.
                {% endblocktrans %}
            </p>
            <div class="feature-columns">
                <div>
                    <i class="fa fa-cubes fa-3x"></i><br>
                    {% blocktrans %}
                    <b>Starter projects</b> provide project layout,
                    scaffolding, already integrated components and
                    ready-to-go code.
                    {% endblocktrans %}
                </div>
                <div>
                    <i class="fa fa-puzzle-piece fa-3x"></i><br>
                    {% blocktrans %}
                    <b>Reusable apps</b> provide common
                    infrastructure, back-end functionality,
                    and user-facing components.
                    {% endblocktrans %}
                </div>
                <div>
                    <i class="fa fa-tint fa-3x"></i><br>
                    {% blocktrans %}
                    <b>Themes</b> provide default templates and
                    stylesheets for quick prototyping and easy customization.
                    {% endblocktrans %}
                </div>
            </div>
        </div>
    </section>
    <section>
        <div class="container">
            <p class="lead text-center">
                {% blocktrans %}
                See <a href="http://pinaxproject.com/">pinaxproject.com</a>
                for more information.
                {% endblocktrans %}
            </p>
        </div>
    </section>
{% endblock %}

scazac/templates/site_base.html
{% extends "base_scazacHeader.djhtml" %} <!-- Modified 20170910 -->

{% load staticfiles %}
{% load pinax_webanalytics_tags %}
{% load i18n %}


{% block styles %}
    {% include "_styles.html" %}
{% endblock %}


{% block extra_head_base %}
    {% block extra_head %}{% endblock %}
{% endblock %}


{% block footer %}
    {% include "_footer.html" %}
{% endblock %}


{% block scripts %}
    {% include "_scripts.html" %}
{% endblock %}

{% block extra_body_base %}
    {% analytics %}
    {% block extra_body %}{% endblock %}
{% endblock %}